In [1]:
import pandas as pd

#Reading Dataset

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.head()

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
0  100.258842         0    3          1           1              1
1   99.079921         0   36          0          -1              0
2  100.054688         0   55          0           0              1
3  100.619414         1   18          0           0              0
4   99.269198         1   82          1           1              0

In [4]:
df.tail()

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
2168  101.749820         1   15          1          -1              0
2169   98.923012         0   29          0           1              0
2170   98.490243         1    9          1          -1              1
2171   98.088675         0   79          1           0              0
2172  101.730738         1   57          1           1              1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2173 entries, 0 to 2172
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   fever          2173 non-null   float64
 1   bodyPain       2173 non-null   int64  
 2   age            2173 non-null   int64  
 3   runnyNose      2173 non-null   int64  
 4   diffBreath     2173 non-null   int64  
 5   infectionProb  2173 non-null   int64  
dtypes: float64(1), int64(5)
memory usage: 102.0 KB


In [6]:
df['diffBreath'].value_counts()

 1    735
-1    727
 0    711
Name: diffBreath, dtype: int64

In [7]:
df.describe()

fever     bodyPain          age    runnyNose   diffBreath  \
count  2173.000000  2173.000000  2173.000000  2173.000000  2173.000000   
mean     99.989932     0.498850    50.408191     0.505292     0.003682   
std       1.146440     0.500114    29.143947     0.500087     0.820426   
min      98.000158     0.000000     1.000000     0.000000    -1.000000   
25%      99.034238     0.000000    25.000000     0.000000    -1.000000   
50%      99.947580     0.000000    50.000000     1.000000     0.000000   
75%     101.003616     1.000000    76.000000     1.000000     1.000000   
max     101.999885     1.000000   100.000000     1.000000     1.000000   

       infectionProb  
count    2173.000000  
mean        0.496088  
std         0.500100  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         1.000000  
max         1.000000

##Train Test Splitting

In [8]:
import numpy as np

In [9]:
def data_split(data, ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_test_size = int(len(data) * ratio)
    test_indices = shuffled[:test_test_size]
    train_indices = shuffled[test_test_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

In [10]:
train, test = data_split(df, 0.2)

In [11]:
train


fever  bodyPain  age  runnyNose  diffBreath  infectionProb
256   101.167146         0    5          0           0              0
1477   98.223235         0   26          0           1              0
555   101.182274         0   69          0           1              0
1472   98.598537         1    9          1           1              1
450   101.500745         0   23          0           1              0
...          ...       ...  ...        ...         ...            ...
1638   98.124497         0   26          1           0              1
1095   98.553217         1   70          1           0              1
1130   99.710097         0   78          1          -1              1
1294   98.219878         1    7          1           0              1
860    99.773531         1   46          0          -1              0

[1739 rows x 6 columns]

In [12]:
test

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
281    99.664557         1   21          0           0              1
1660  101.259424         0   70          0           1              1
2024  101.423309         1   62          0           1              0
620   100.447240         0   81          0           1              0
2085   99.810235         0   69          1           1              1
...          ...       ...  ...        ...         ...            ...
942    98.692500         1   50          1          -1              1
1083  101.189242         0   39          1          -1              1
1286  101.848480         0   33          0           0              1
861   100.655696         1   49          1           0              0
903   100.232112         0   45          0           1              0

[434 rows x 6 columns]

In [13]:
X_train = train[['fever','bodyPain','age','runnyNose','diffBreath']].to_numpy()

In [14]:
X_train

array([[101.1671457 ,   0.        ,   5.        ,   0.        ,
          0.        ],
       [ 98.2232352 ,   0.        ,  26.        ,   0.        ,
          1.        ],
       [101.1822739 ,   0.        ,  69.        ,   0.        ,
          1.        ],
       ...,
       [ 99.71009744,   0.        ,  78.        ,   1.        ,
         -1.        ],
       [ 98.21987829,   1.        ,   7.        ,   1.        ,
          0.        ],
       [ 99.77353148,   1.        ,  46.        ,   0.        ,
         -1.        ]])

In [15]:
X_test = test[['fever','bodyPain','age','runnyNose','diffBreath']].to_numpy()

In [16]:
X_test

array([[ 99.66455709,   1.        ,  21.        ,   0.        ,
          0.        ],
       [101.2594245 ,   0.        ,  70.        ,   0.        ,
          1.        ],
       [101.4233088 ,   1.        ,  62.        ,   0.        ,
          1.        ],
       ...,
       [101.8484798 ,   0.        ,  33.        ,   0.        ,
          0.        ],
       [100.6556963 ,   1.        ,  49.        ,   1.        ,
          0.        ],
       [100.2321118 ,   0.        ,  45.        ,   0.        ,
          1.        ]])

In [17]:
Y_train = train[['infectionProb']].to_numpy().reshape(1739, )
Y_test = test[['infectionProb']].to_numpy().reshape(434, )

In [18]:
Y_train


array([0, 0, 0, ..., 1, 1, 0], dtype=int64)

In [19]:
Y_test

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,

In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
clf = LogisticRegression()
clf.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [22]:
inputFeatures = [90, 0 , 25, 0, -1]
infProb = clf.predict_proba([inputFeatures])[0][1]*100

In [23]:
infProb


52.58566129912718